In [2]:
import numpy as np

In [3]:
v=np.array([3,2,3])
print(v)

[3 2 3]


In [5]:
mat=np.zeros((3,4))
print(mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
mat=np.ones((3,3))
print(mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
mat_1=np.full((3,3),5)
print(mat_1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [15]:
mat_2=np.empty((3,3))
mat_2

array([[0.71414689, 0.29992934, 0.22757505],
       [0.27817481, 0.88876668, 0.39625996],
       [0.18907404, 0.06667059, 0.8490881 ]])

In [10]:
angle=np.arange(0,361,90)
print(angle)

[  0  90 180 270 360]


In [12]:
vec=np.linspace(0,10,num=10)
print(vec)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [13]:
iden=np.identity(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
np.random.random((3,3))

array([[0.71414689, 0.29992934, 0.22757505],
       [0.27817481, 0.88876668, 0.39625996],
       [0.18907404, 0.06667059, 0.8490881 ]])

In [16]:
np.random.randint(1, 10, (3, 3))

array([[2, 6, 3],
       [2, 2, 7],
       [4, 3, 7]], dtype=int32)

In [19]:
a=['ali','om',False]
m=np.random.choice(a,size=(3,5))
print(m)

[['ali' 'om' 'False' 'False' 'ali']
 ['ali' 'om' 'om' 'om' 'om']
 ['om' 'False' 'False' 'ali' 'ali']]


In [21]:
matt_1=np.ones((3,4))
mat_2=np.zeros((5,3))
np.savez('test_save.npz',Ones_Mat=matt_1,Zeros_Mat=mat_2)

In [23]:
with np.load('test_save.npz') as file:
    mat_1=file['Ones_Mat']
    mat_2=file['Zeros_Mat']



In [24]:
mat_2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:

m1=np.array([[1,2,3],
            [4,5,6]])

m2=np.array([[7,8,9],
            [0,0,0]])
new_stack_v=np.vstack((m1,m2))
print(new_stack_v)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 0 0]]


In [31]:
new_stack_h=np.hstack((m1,m2))
print(new_stack_h)

[[1 2 3 7 8 9]
 [4 5 6 0 0 0]]


In [35]:
#Comparison

v1=np.array([1,2,3,4,10])
v2=np.array([1,2,3,5,10])
v1==v2

array([ True,  True,  True, False,  True])

In [37]:
v1=np.array([1,2,3,4,10])
print(np.all(v1>2))

False


In [38]:
v1=np.array([1,2,3,4,10])
print(np.any(v1>2))

True


In [39]:
np.isclose(v1,v2,atol=1)


array([ True,  True,  True,  True,  True])

In [41]:
import pandas as pd

In [44]:
s=pd.Series([1,2,3,4],index=['A','B','C','D'])
s

A    1
B    2
C    3
D    4
dtype: int64

In [45]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]
data
 

[[1, 444, 'abc'], [2, 555, 'def'], [3, 666, 'ghi'], [4, 444, 'xyz']]

In [53]:
df=pd.DataFrame(data,columns=['index','uid','dept'])
df

index  uid dept
0      1  444  abc
1      2  555  def
2      3  666  ghi
3      4  444  xyz

In [59]:
df['index']= df['index'].astype('int')
df.dtypes

index     int64
uid       int64
dept     object
dtype: object

In [60]:
df.tail(2)

index  uid dept
2      3  666  ghi
3      4  444  xyz

In [61]:
df.describe(include='number')

index         uid
count  4.000000    4.000000
mean   2.500000  527.250000
std    1.290994  106.274409
min    1.000000  444.000000
25%    1.750000  444.000000
50%    2.500000  499.500000
75%    3.250000  582.750000
max    4.000000  666.000000

In [63]:
df.columns

Index(['index', 'uid', 'dept'], dtype='object')

In [64]:
df['uid'].unique()

array([444, 555, 666])

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   index   4 non-null      int64 
 1   uid     4 non-null      int64 
 2   dept    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes


In [66]:
df['uid'].iloc[0:2]

0    444
1    555
Name: uid, dtype: int64

In [67]:
new_col=df['index']+df['uid']

In [69]:
df.insert(3,'new',new_col)

In [70]:
df

index  uid dept  new
0      1  444  abc  445
1      2  555  def  557
2      3  666  ghi  669
3      4  444  xyz  448

In [71]:
df.drop('new', axis=1)

index  uid dept
0      1  444  abc
1      2  555  def
2      3  666  ghi
3      4  444  xyz