# NumPy Programming Assignment

Part 1: Smart Array Factory
Task: Create a function that allows students to generate specific array types quickly using built-in NumPy methods.


In [12]:
import numpy as np

mode=input('choes mode(zeros,ones,full,identity):')
shape=tuple(map(int,input('enter the shape of the array like 2,3 :').split(',')))
value=int(input('enter the value:'))
def array_factory(mode, shape, value):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode =='zeros':
        return np.zeros(shape)
    elif mode =='ones':
        return np.ones(shape)
    elif mode =='full':
        return np.full(shape,value)
    elif mode =='identity':
        return np.identity(shape)
    else:
        raise ValueError(f"Invalid mode: {mode}")

array_factory(mode,shape,value)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Part 2: The secure_reshape_and_stack Function.

This function demonstrates how to handle data integration by transforming a flat data structure into a matrix and then combining it with an existing dataset

In [5]:
import numpy as np

def secure_reshape_and_stack(data1, data2, new_shape):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        
        reshaped_arr1 = arr1.reshape(new_shape)

     
        combined_dataset = np.vstack([reshaped_arr1, arr2])

        return combined_dataset

    except ValueError as e:
     
        raise ValueError(f"Company-grade Error: {e}")

data1 = list(range(1, 26))  
data2 = [[26, 27, 28, 29, 30], [31, 32, 33, 34, 35]]  
result = secure_reshape_and_stack(data1, data2, (5, 5))
print("Success! Result shape:", result.shape)
print(result)


Success! Result shape: (7, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


part-3 The apply_threshold Function.

This function demonstrates Conditional Access and Modification, which are primarily used in data cleaning and processing. It follows the logic of identifying specific elements based on a boolean condition and replacing them efficiently.

In [7]:
import numpy as np

def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr = np.array(arr)
    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array 
    condition = arr >= threshold
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    modified_arr = np.where(condition, replacement_value, arr)
    
    return modified_arr

# Example usage:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
threshold = 5
result = apply_threshold(arr, threshold, replacement_value=-1)
print(f"Original array: {arr}")
print(f"Threshold: {threshold}")
print(f"Modified array: {result}")
print(f"Elements >= {threshold} were replaced with -1")

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Threshold: 5
Modified array: [ 1  2  3  4 -1 -1 -1 -1 -1 -1]
Elements >= 5 were replaced with -1


TestCase

In [8]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print("Final Report:")
print(final_report)
print(f"\nResulting shape: {final_report.shape}")  # Should be (4, 3)

Final Report:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Resulting shape: (4, 3)


In [ ]:
v = np.array([1, 2, 3])
result = apply_threshold(v, 2, -20)
print(f"Original array: {v}")
print(f"Threshold: 2")
print(f"Modified array: {result}")
print(f"Elements >= 2 were replaced with -20")


array([  1, -20, -20])